### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by slayerwalt** [LingXuanYin/YueHaiXianLin#2]
### FileNotFoundError
下载后直接运行有如下报错
![image](https://user-images.githubusercontent.com/77372975/215319631-35582f51-ea4e-4873-b2a8-17acd70afa71.png)

环境：Windows11
Python3.9.12

**Comment by LingXuanYin** [comment]
pyecharts打包资源问题，已解决，请下载最新的releases[https://github.com/LingXuanYin/YueHaiXianLin/releases/tag/月海仙麟](url)
